# Generated by Django 3.2.8 on 2021-10-28 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_appointments', '0002_auto_20211025_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='RolesUsers',
        ),
        migrations.AlterModelOptions(
            name='rolesusers',
            options={'verbose_name': 'Roles User', 'verbose_name_plural': 'Roles User'},
        ),
    ]
