# Generated by Django 3.2.8 on 2021-10-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_appointments', '0003_auto_20211028_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolesusers',
            old_name='id_user',
            new_name='users',
        ),
    ]
