# Generated by Django 3.2.8 on 2021-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_appointments', '0004_rename_id_user_rolesusers_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='rolesusers',
            options={'verbose_name': 'Role User', 'verbose_name_plural': 'Roles User'},
        ),
    ]
