# Generated by Django 3.2.8 on 2021-11-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_appointments', '0005_auto_20211103_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provider', models.SmallIntegerField()),
                ('id_section', models.CharField(choices=[('SECTION_ONE', 'Secition one'), ('SECTION_TWO', 'Section two'), ('SECTION_THREE', 'Section three'), ('SECTION_FOUR', 'Section four')], max_length=100)),
                ('configuraions', models.JSONField()),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
    ]
